### ISSUE TITLE
Move file upload process to S3 

### ISSUE THREAD

**Issue by karthikmuralidharan** [etherlabsio/avcapture#16]
**Goals**

Deprecate Recordersvc in Ether 

**Tasks**

- [ ] Add segment watcher.
- [ ] Upload to a bucket with appropriate key paths when provided with a handle.
- [ ] Update deloreansvc to call avcapture over HTTP rather than calling the recordersvc.
